CREATE TABLE IF NOT EXISTS sso_providers (
    id                   BIGINT                NOT NULL AUTO_INCREMENT PRIMARY KEY,
    slug                 VARCHAR(64)           NOT NULL,
    display_name         VARCHAR(255)          NOT NULL,
    kind                 ENUM('oidc','oauth2') NOT NULL DEFAULT 'oidc',
    issuer_url           TEXT                  NULL,
    authorize_url        TEXT                  NULL,
    token_url            TEXT                  NULL,
    userinfo_url         TEXT                  NULL,
    jwks_url             TEXT                  NULL,
    introspect_url       TEXT                  NULL,
    client_id            VARCHAR(255)          NULL,
    client_secret_ref    VARCHAR(255)          NULL,
    client_secret_enc    TEXT                  NULL,
    scopes               VARCHAR(512)          NOT NULL DEFAULT 'openid email profile',
    email_claim          VARCHAR(128)          NOT NULL DEFAULT 'email',
    email_verified_claim VARCHAR(128)          NOT NULL DEFAULT 'email_verified',
    subject_claim        VARCHAR(128)          NOT NULL DEFAULT 'sub',
    button_label         VARCHAR(255)          NULL,
    allow_auto_link      TINYINT(1)            NOT NULL DEFAULT 0,
    auto_provision       TINYINT(1)            NOT NULL DEFAULT 1,
    enabled              TINYINT(1)            NOT NULL DEFAULT 1,
    inserted_at          DATETIME              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_sso_providers_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
