package structs

import "time"

// IssueStatus is the single lifecycle axis for an issue.
//
// There is deliberately not a second "workflow" axis. Automated recurrence only
// ever transitions OUT of StatusResolved (see query.UpsertIssueOccurrence), so an
// agent holding StatusInProgress through a recurrence is never clobbered — which
// was the only thing a second axis would have bought. StatusUnresolved is both
// the default for a new issue and the backlog.
type IssueStatus string

const (
	IssueStatusUnresolved IssueStatus = "unresolved"
	IssueStatusInProgress IssueStatus = "in_progress"
	IssueStatusResolved   IssueStatus = "resolved"
	IssueStatusIgnored    IssueStatus = "ignored"
)

// IsValid reports whether the status is one of the known values.
func (s IssueStatus) IsValid() bool {
	switch s {
	case IssueStatusUnresolved, IssueStatusInProgress, IssueStatusResolved, IssueStatusIgnored:
		return true
	}
	return false
}

// IssuePriority is an optional triage weight. Unset is normal — priority is a
// human signal, not something ingestion infers.
type IssuePriority string

const (
	IssuePriorityLow      IssuePriority = "low"
	IssuePriorityMedium   IssuePriority = "medium"
	IssuePriorityHigh     IssuePriority = "high"
	IssuePriorityCritical IssuePriority = "critical"
)

// IsValid reports whether the priority is one of the known values.
func (p IssuePriority) IsValid() bool {
	switch p {
	case IssuePriorityLow, IssuePriorityMedium, IssuePriorityHigh, IssuePriorityCritical:
		return true
	}
	return false
}

// Issue is a group of error events sharing a fingerprint, plus the triage state
// carried on top of it. Lives in MariaDB (monitor.issues).
//
// ID is not generated by the database. It is the deterministic UUIDv5 minted by
// issues.issueIDFor(fingerprint), so concurrent creators converge on one row.
//
// NOTE: issues.Issue is the older ClickHouse-backed shape and is still what the
// handlers return today. It is superseded by this struct when processError and
// the read paths are cut over to MariaDB.
type Issue struct {
	ID              string         `json:"id"`
	Fingerprint     string         `json:"fingerprint"`
	Service         string         `json:"service"`
	Name            string         `json:"name"`
	Message         *string        `json:"message"`
	Path            *string        `json:"path"`
	Status          IssueStatus    `json:"status"`
	Priority        *IssuePriority `json:"priority,omitempty"`
	Title           *string        `json:"title,omitempty"`
	AssigneeUserID  *int64         `json:"assignee_user_id,omitempty"`
	OccurrenceCount uint64         `json:"occurrence_count"`
	RegressionCount int            `json:"regression_count"`
	FirstSeen       *time.Time     `json:"first_seen"`
	LastSeen        *time.Time     `json:"last_seen"`
	ResolvedAt      *time.Time     `json:"resolved_at,omitempty"`
	RegressedAt     *time.Time     `json:"regressed_at,omitempty"`
	InsertedAt      time.Time      `json:"inserted_at"`
	UpdatedAt       time.Time      `json:"updated_at"`

	// Assignee is joined from monitor_auth.users when requested. There is no
	// foreign key behind AssigneeUserID, so this can be nil for a user that no
	// longer exists.
	Assignee *User `json:"assignee,omitempty"`
	// Links is populated by the detail read, not the list read.
	Links []IssueLink `json:"links,omitempty"`
	// CommentCount counts non-deleted timeline entries of type comment.
	CommentCount *int `json:"comment_count,omitempty"`
}
