package query

import (
	"database/sql"
	"fmt"
	"time"

	sq "github.com/Masterminds/squirrel"
	"github.com/aidenappl/monitor-core/db"
	"github.com/aidenappl/monitor-core/structs"
)

var apiKeyColumns = []string{
	"id", "name", "key_hash", "key_prefix", "scope", "created_at", "last_used_at",
}

type apiKeyScanner interface {
	Scan(dest ...interface{}) error
}

func scanAPIKey(row apiKeyScanner) (*structs.APIKey, error) {
	var k structs.APIKey
	var scope string
	if err := row.Scan(&k.ID, &k.Name, &k.KeyHash, &k.KeyPrefix, &scope, &k.CreatedAt, &k.LastUsedAt); err != nil {
		return nil, err
	}
	k.Scope = structs.Scope(scope)
	return &k, nil
}

// ListAPIKeys returns every stored API key (including key_hash, which callers
// must not serialize) ordered newest-first.
func ListAPIKeys(engine db.Queryable) ([]structs.APIKey, error) {
	query, args, err := sq.Select(apiKeyColumns...).
		From("api_keys").
		OrderBy("created_at DESC").
		ToSql()
	if err != nil {
		return nil, fmt.Errorf("build query: %w", err)
	}

	rows, err := engine.Query(query, args...)
	if err != nil {
		return nil, fmt.Errorf("list api keys: %w", err)
	}
	defer rows.Close()

	keys := []structs.APIKey{}
	for rows.Next() {
		k, err := scanAPIKey(rows)
		if err != nil {
			return nil, fmt.Errorf("scan api key: %w", err)
		}
		keys = append(keys, *k)
	}
	return keys, rows.Err()
}

// GetAPIKeyByID resolves a single key. Returns (nil, nil) when not found.
func GetAPIKeyByID(engine db.Queryable, id string) (*structs.APIKey, error) {
	query, args, err := sq.Select(apiKeyColumns...).
		From("api_keys").
		Where(sq.Eq{"id": id}).
		ToSql()
	if err != nil {
		return nil, fmt.Errorf("build query: %w", err)
	}

	k, err := scanAPIKey(engine.QueryRow(query, args...))
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("get api key: %w", err)
	}
	return k, nil
}

type CreateAPIKeyRequest struct {
	ID        string
	Name      string
	KeyHash   string
	KeyPrefix string
	Scope     structs.Scope
	CreatedAt time.Time
}

// CreateAPIKey inserts a new key row. The raw key/prefix/hash are generated by
// the caller (apikeys package).
func CreateAPIKey(engine db.Queryable, req CreateAPIKeyRequest) error {
	query, args, err := sq.Insert("api_keys").
		Columns("id", "name", "key_hash", "key_prefix", "scope", "created_at").
		Values(req.ID, req.Name, req.KeyHash, req.KeyPrefix, string(req.Scope), req.CreatedAt).
		ToSql()
	if err != nil {
		return fmt.Errorf("build query: %w", err)
	}

	if _, err := engine.Exec(query, args...); err != nil {
		return fmt.Errorf("create api key: %w", err)
	}
	return nil
}

// DeleteAPIKey hard-deletes a key by id.
func DeleteAPIKey(engine db.Queryable, id string) error {
	query, args, err := sq.Delete("api_keys").Where(sq.Eq{"id": id}).ToSql()
	if err != nil {
		return fmt.Errorf("build query: %w", err)
	}

	if _, err := engine.Exec(query, args...); err != nil {
		return fmt.Errorf("delete api key: %w", err)
	}
	return nil
}
